export enum DIName {
  App = 'App',
  Logger = 'Logger',
  Config = 'Config',
  UserRepository = 'UserRepository',
  UserModel = 'UserModel',
  OfferRepository = 'OfferRepository',
  OfferModel = 'OfferModel',
  DBClient = 'DBClient',
  CommentRepository = 'CommentRepository',
  CommentModel = 'CommentModel',
  UserController = 'UserController',
  OfferController = 'OfferController',
  CommentController = 'CommentController',
  ExceptionFilter = 'ExceptionFilter',
}
